options:
  formatter: stylish

files:
  include: 'boneless/**/*.scss'

rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-warn: 1
  no-color-keywords: 1
  no-invalid-hex: 1
  no-css-comments: 1
  no-color-literals: 1

  # Style Guide
  border-zero: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation:
    - 1
    -
      size: 2
  leading-zero:
    - 1
    -
      include: true
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 1
    -
      order: recess
  quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
