language: node_js
node_js:
  - '4.0.0'
  - '0.12'
before_install: npm install -g parker node-sass eyeglass postcss autoprefixer
install: npm install
script: npm run build
after_success:
  - parker test/boneless.css
notifications:
  email: false
  slack:
    secure: cKVNcxjxaUzKZp+upfzGHfrjaYbRyR2UZROMWnw03rmJTbAejmem59ahgRWjaNXUtzgtgFdobgJY/rrQlCrsqRGUlnbN75p40HMnjJcEZlp6SdsHfv/1Uwvn5UD0dFhe7eOI075yG5n0YYx4924W3qFvTitDMMkyGoLIKdIpQf8=
