language: node_js
node_js:
  - '4.0.0'
  - '0.12'
before_install:
  - gem install sass
  - npm install -g parker node-sass
install: npm install
script:
  - node-sass --output-style nested --precision 10 boneless.scss bin/boneless.css
  - sass -t nested --precision 10 -C boneless.scss bin/boneless.css
after_success:
  - gulp build
  - parker bin/boneless.css
notifications:
  email: false
  slack:
    secure: cKVNcxjxaUzKZp+upfzGHfrjaYbRyR2UZROMWnw03rmJTbAejmem59ahgRWjaNXUtzgtgFdobgJY/rrQlCrsqRGUlnbN75p40HMnjJcEZlp6SdsHfv/1Uwvn5UD0dFhe7eOI075yG5n0YYx4924W3qFvTitDMMkyGoLIKdIpQf8=
